#!/usr/bin/env python3
"""Emit src/synafp_tables.c: device identification and per-type capture data.

Run this only when adding support for a new sensor. The generated file is
committed, so building synafp never requires python-validity to be installed.

    python3 tools/gen_tables.py > src/synafp_tables.c

Requires python-validity importable, since the capture programs, sensor
geometry and initialisation blobs originate in the Synaptics Windows driver
and that project already extracts them.
"""
import importlib
import sys

from validitysensor.hw_tables import dev_info_table
from validitysensor.table_types import SensorTypeInfo, SensorCaptureProg

# Sensor types we ship capture data for, with the constants the vendor driver
# hardcodes per type, and the ROM identity to select a capture program with.
#
#   key_line: which calibration line is spliced into the timeslot table
#   frames/iters: calibration capture parameters
#   lu_type: line-update variant (1 or 2)
SUPPORTED = {
    0x199: dict(key_line=0x38, frames=3, iters=3, lu_type=1,
                rom=(0x545eb0f0, 164, 6, 7, 48, 0)),
}

# Per-device initialisation blobs, by USB id.
DEVICES = [
    (0x06cb, 0x009a, "validitysensor.blobs_9a"),
    (0x138a, 0x0090, "validitysensor.blobs_90"),
    (0x138a, 0x0097, "validitysensor.blobs_97"),
    (0x138a, 0x009d, "validitysensor.blobs_9d"),
]

BLOBS = ["init_hardcoded", "init_hardcoded_clean_slate", "db_write_enable"]


def carray(name, data):
    out = ["static const uint8_t %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 12):
        out.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",")
    out.append("};")
    return "\n".join(out)


def cstring(s):
    return '"%s"' % "".join(
        c if 32 <= ord(c) < 127 and c not in '"\\' else "\\x%02x" % ord(c)
        for c in s.strip()
    )


def main():
    w = sys.stdout.write
    w("/* synafp_tables.c - GENERATED by tools/gen_tables.py, do not edit.\n"
      " *\n"
      " * Device identification, per-type capture data and initialisation\n"
      " * blobs. These values originate in the Synaptics Windows driver and\n"
      " * are reproduced the same way python-validity distributes them.\n"
      " *\n"
      " * SPDX-License-Identifier: LGPL-2.1-or-later\n"
      " */\n"
      '#include "synafp_priv.h"\n\n')

    # --- device identification -------------------------------------------
    w("/* Maps the (major, version) pair reported by command 0x75 to a sensor\n"
      " * type. Matching follows the vendor rules: an exact masked version wins,\n"
      " * otherwise a zero mask or zero version is a fuzzy fallback. */\n")
    w("const syna_dev_info syna_dev_info_table[] = {\n")
    for i in dev_info_table:
        w("    { 0x%04x, 0x%04x, 0x%02x, 0x%02x, %s },\n"
          % (i.major, i.type, i.version, i.version_mask, cstring(i.name)))
    w("};\n\n")
    w("const int syna_dev_info_table_len =\n"
      "    (int) (sizeof syna_dev_info_table / sizeof syna_dev_info_table[0]);\n\n")

    # --- per-type capture data -------------------------------------------
    entries = []
    for t, cfg in sorted(SUPPORTED.items()):
        ti = SensorTypeInfo.get_by_type(t)
        if ti is None:
            raise SystemExit("no SensorTypeInfo for type 0x%x" % t)

        rom = type("Rom", (), dict(zip(
            ("timestamp", "build", "major", "minor", "product", "u1"), cfg["rom"])))()
        prog = SensorCaptureProg.get(rom, t, 0x18, 0x19)
        if prog is None:
            raise SystemExit("no capture program for type 0x%x" % t)

        w(carray("prog_%04x" % t, bytes(prog)) + "\n\n")
        w(carray("calib_%04x" % t, ti.calibration_blob) + "\n\n")
        entries.append((t, ti, cfg))

    w("const syna_type_info syna_type_table[] = {\n")
    for t, ti, cfg in entries:
        w("    { 0x%04x, %d, %d, %d, %d, 0x%02x, %d, %d, %d,\n"
          "      prog_%04x, sizeof prog_%04x, calib_%04x, sizeof calib_%04x },\n"
          % (t, ti.bytes_per_line, ti.line_width, ti.repeat_multiplier,
             ti.lines_per_calibration_data, cfg["key_line"], cfg["frames"],
             cfg["iters"], cfg["lu_type"], t, t, t, t))
    w("};\n\n")
    w("const int syna_type_table_len =\n"
      "    (int) (sizeof syna_type_table / sizeof syna_type_table[0]);\n\n")

    # --- initialisation blobs --------------------------------------------
    devs = []
    for vid, pid, mod in DEVICES:
        try:
            m = importlib.import_module(mod)
        except ImportError:
            sys.stderr.write("skipping %04x:%04x (%s unavailable)\n" % (vid, pid, mod))
            continue
        names = {}
        ok = True
        for b in BLOBS:
            data = getattr(m, b, None)
            if data is None:
                sys.stderr.write("skipping %04x:%04x (%s lacks %s)\n" % (vid, pid, mod, b))
                ok = False
                break
            sym = "%s_%04x_%04x" % (b, vid, pid)
            names[b] = (sym, bytes(data))
        if not ok:
            continue
        for b in BLOBS:
            sym, data = names[b]
            w(carray(sym, data) + "\n\n")
        devs.append((vid, pid, names))

    w("const syna_dev_blobs syna_blob_table[] = {\n")
    for vid, pid, names in devs:
        w("    { 0x%04x, 0x%04x,\n" % (vid, pid))
        for b in BLOBS:
            sym, _ = names[b]
            w("      %s, sizeof %s,\n" % (sym, sym))
        w("    },\n")
    w("};\n\n")
    w("const int syna_blob_table_len =\n"
      "    (int) (sizeof syna_blob_table / sizeof syna_blob_table[0]);\n")


if __name__ == "__main__":
    main()
