#!/usr/bin/env python3
"""Emit src/synafp_tables.c for the sensor types synafp supports.

The capture programs and per-type geometry originate in Synaptics' Windows
driver; python-validity extracts them into a generated module, and this script
lifts only the entries synafp needs into C. Run it only when adding support
for a new sensor type; the generated file is committed so that building synafp
never depends on python-validity being installed.

    python3 tools/gen_tables.py > src/synafp_tables.c
"""
import sys
from validitysensor.table_types import SensorTypeInfo, SensorCaptureProg

# (vendor, product) -> python-validity blob module holding that unit's
# initialisation blobs.
DEVICES = [(0x06cb, 0x009a, "validitysensor.blobs_9a")]
BLOBS = ["init_hardcoded", "init_hardcoded_clean_slate", "db_write_enable"]


class Rom:
    """ROM identity of the reference unit (ThinkPad X1 Yoga gen 3, 06cb:009a)."""
    timestamp, build, major, minor, product, u1 = 0x545eb0f0, 164, 6, 7, 48, 0


TYPES = [0x199]


def carray(name, data):
    out = ["static const uint8_t %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 12):
        row = ", ".join("0x%02x" % b for b in data[i:i + 12])
        out.append("    %s," % row)
    out.append("};")
    return "\n".join(out)


def main():
    w = sys.stdout.write
    w("/* synafp_tables.c - GENERATED by tools/gen_tables.py, do not edit.\n"
      " *\n"
      " * Capture programs and sensor geometry for the supported sensor types.\n"
      " * These values originate in the Synaptics Windows driver and are\n"
      " * reproduced here the same way python-validity distributes them.\n"
      " *\n"
      " * SPDX-License-Identifier: LGPL-2.1-or-later\n"
      " */\n"
      '#include "synafp_priv.h"\n\n')

    entries = []
    for t in TYPES:
        ti = SensorTypeInfo.get_by_type(t)
        prog = SensorCaptureProg.get(Rom(), t, 0x18, 0x19)
        if ti is None or prog is None:
            raise SystemExit("no tables for sensor type 0x%x" % t)
        prog = bytes(prog)
        w(carray("prog_%04x" % t, prog) + "\n\n")
        w(carray("calib_%04x" % t, ti.calibration_blob) + "\n\n")
        entries.append((t, ti, prog))

    w("const syna_type_info syna_type_table[] = {\n")
    for t, ti, prog in entries:
        w("    { 0x%04x, %d, %d, %d, %d, prog_%04x, sizeof prog_%04x,\n"
          "      calib_%04x, sizeof calib_%04x },\n"
          % (t, ti.bytes_per_line, ti.line_width, ti.repeat_multiplier,
             ti.lines_per_calibration_data, t, t, t, t))
    w("};\n\n")
    w("const int syna_type_table_len =\n"
      "    (int) (sizeof syna_type_table / sizeof syna_type_table[0]);\n\n")

    # Per-device initialisation blobs. The sensor rejects capture programs
    # until it has been initialised with these.
    import importlib
    devs = []
    for vid, pid, mod in DEVICES:
        m = importlib.import_module(mod)
        names = {}
        for b in BLOBS:
            data = getattr(m, b, None)
            if data is None:
                raise SystemExit("%s lacks %s" % (mod, b))
            sym = "%s_%04x" % (b, pid)
            w(carray(sym, bytes(data)) + "\n\n")
            names[b] = sym
        devs.append((vid, pid, names))

    w("const syna_dev_blobs syna_blob_table[] = {\n")
    for vid, pid, names in devs:
        w("    { 0x%04x, 0x%04x,\n" % (vid, pid))
        for b in BLOBS:
            w("      %s, sizeof %s,\n" % (names[b], names[b]))
        w("    },\n")
    w("};\n\n")
    w("const int syna_blob_table_len =\n"
      "    (int) (sizeof syna_blob_table / sizeof syna_blob_table[0]);\n")


if __name__ == "__main__":
    main()
